### ISSUE TITLE
Protocol error on Visual Studio

### ISSUE THREAD

**Issue by ad-l** [project-everest/everest#10]
I use plink.exe with pageant on Windows.
Cloning Spartan fails with the following error:
```fatal: protocol error: bad line length character: msre```

**Comment by msprotz** [comment]
Hmm I don't have that setup. Do you know what's going wrong?

I recently made it so that it would install Cygwin's git -- windows git has all sorts of issues. I can double-check that we're running Cygwin's git... but that would only sidestep the problem.

**Comment by ad-l** [comment]
The error is quite cryptic but debugging with putty it is actually an authentication problem. (I am using Cygwin git but with GIT_SSH=plink.exe to use pageant to manage the private key).
I fixed it by switching to an RSA private key on the Visual Studio online manager (https://msresearch.visualstudio.com/_details/security/keys)

**Comment by msprotz** [comment]
@darrenge had a similar problem which I also solved by making sure he would authenticate using SSH keys. Hopefully this will go away once Spartan moves to github.

**Comment by ad-l** [comment]
I think the SSH implementation of the VS server is a bit wonky and doesn't like Curve25519. Moving Spartan to GitHub will certainly solve this
