### ISSUE TITLE
uninstall 

### ISSUE THREAD

**Issue by sishtiaq** [project-everest/everest#11]
Add a `everest uninstall` function. This reverses everything that `check`, `pull`, `make` did, leaving your machine back in it's original state.

**Comment by s-zanella** [comment]
This is very difficult to implement without keeping track of what the script did (think saving an OPAM snapshot, reverting changes to `.bash_profile`, creating local branches before pulling, etc.).
The best way to revert changes locally remains `git clean -ffdx` (deletes the clones of all subprojects), or `./everest forall git clean -ffdx` to revert all sub-projects to a clean slate.
