### ISSUE TITLE
Check for OpenSSL development files

### ISSUE THREAD

**Issue by BarryBo** [project-everest/everest#19]
My Ubuntu comes with OpenSSL executables but not the libssl-dev package.

FStar/ucontrib/corecrypto depends on openssl.h and its build errors out if it isn't present, with warnings about many things.  Here are the first two:

793 lines of outputopenssl_stub.c: In function ‘ocaml_openssl_init’:
openssl_stub.c:93:3: warning: implicit declaration of function ‘OPENSSL_config’ [-Wimplicit-function-declaration]
   OPENSSL_config("CoreCrypto");
   ^
openssl_stub.c: In function ‘ocaml_rsa_gen_key’:
openssl_stub.c:668:23: warning: passing argument 2 of ‘RSA_get0_key’ from incompatible pointer type [-Wincompatible-pointer-types]
     RSA_get0_key(rsa, &b_n, &b_e, &b_d);
                       ^

**Comment by s-zanella** [comment]
`FStar/ucontrib/corecrypto` is deprecated in favor of https://github.com/project-everest/MLCrypto, which has an OpenSSL submodule. Hopefully we'll deprecate this soon too and remove all dependencies on OpenSSL.
