### ISSUE TITLE
Create a CI for Vale

### ISSUE THREAD

**Issue by BarryBo** [project-everest/everest#21]
We should set up Continuous Integration for Vale, building on 32-bit and 64-bit Windows, as well as Linux, mirroring the configurations that the ./everest script uses.

The current, undocumented, policy, is to have contributors push directly to master, and wait for the everest build to try and roll forward to the new head in vale.

**Comment by msprotz** [comment]
@darrenge can we repurpose the existing definitions for Spartan that used to run?

**Comment by darrenge** [comment]
Yeah we can once we know the calls to make etc. Currently it is calling nmake.

**Comment by msprotz** [comment]
We're building Vale as part of everest, so the right invocations are listed in the everest script at https://github.com/project-everest/everest/blob/master/everest#L556 -- this should be easily transferrable, assuming you have the things in the PATH

**Comment by darrenge** [comment]
So we are on the same page ... you are talking making those everest calls from the ci script ... right?

**Comment by msprotz** [comment]
That would be the simplest way, in my opinion, yes, since the code is already there.

**Comment by darrenge** [comment]
-[ ] Windows CI - x86
-[ ] Windows CI - x64
-[ ] Linux CI

**Comment by darrenge** [comment]
This is done ... so can close
