### ISSUE TITLE
SCons check broken on Windows

### ISSUE THREAD

**Issue by andreas23** [project-everest/everest#23]
The everest script doesn't properly check for SCons on Windows, it merely checks whether Python 2.7 is installed. It also doesn't install SCons, even though it installs everything else needed.

**Comment by sishtiaq** [comment]
Hi @andreas23, 

Not the answer to your question but this (manual) process got me scons running on Windows+Cygwin:

1. Install python 32-bit. Allow the installer to add python to your %PATH% (by default, it doesn't);
2. Install scons. (If you had installed python 64-bit, scons complains "Python...not found in the registry"; it will only find python if you installed the 32-bit one);

scons.bat should be in Cygwin's $PATH (inherited from Windows %PATH%) now:
```
$ which scons.bat
/cygdrive/c/Python27/Scripts/scons.bat
```

**Comment by andreas23** [comment]
Mhh. I have a hard time testing this, because the script now tries to re-install everything. I'll try to find out what's broken. I've had a look at the patches on this branch though, and they look good enough to me.

**Comment by sishtiaq** [comment]
Branch merged. The script is no different in terms of install. Maybe you can copy the output from your run of the script, so we can help you debug?

**Comment by andreas23** [comment]
Kicked a few things (interfering other POSIXy stuff on the path), and it's working just fine now.
