### ISSUE TITLE
phantom "disk full" error during hacl-star build

### ISSUE THREAD

**Issue by andreas23** [project-everest/everest#27]
When running the everest build, during the hacl-star build phase, I run into a "disk full" error:

178 lines of outputWarning 7: : After inlining, Hacl.Test.Chacha20.main calls Hacl.Symmetric.Chacha20.chacha20_finish -- removing the static qualifier from Hacl.Symmetric.Chacha20.chacha20_finish
302 lines of outputFatal error: exception Sys_error("No space left on device")

That's not the case, though:

bogk@4DELBOGK ~/everest
$ df .
Filesystem     1K-blocks      Used Available Use% Mounted on
C:             249174012 239811572   9362440  97% /cygdrive/c

And manually calling:

$ make -C hacl-star/code extract-c -j 15

Just works fine and goes through.

**Comment by jkzinzindohoue** [comment]
On which branch is this ?
Last time we hit that it was due to the extraction being too verbose and filling up the pipe. Removing the `-verbose` argument to KreMLin solved it, although I left some to help debugging CI issues.

**Comment by andreas23** [comment]
That's all on master, not older than 24 hours. Let me see whether I find the right -verbose...

**Comment by andreas23** [comment]
Indeed, removing -verbose from the KreMLin call for Salsa20 in hacl-star/code/salsa-family/Makefile makes it work. And with that, "everest make" works for me!

**Comment by andreas23** [comment]
Interestingly enough, the bug vanished.
