### ISSUE TITLE
Write a Powershell script that automates the first step on Windows

### ISSUE THREAD

**Issue by msprotz** [project-everest/everest#4]
Namely: downloading Cygwin's setup-x86_64.exe, then launching it with the right set of commands, opening up a mintty and launching this script.

**Comment by msprotz** [comment]
This should also install git so that the powershell script can launch `bash -c "git clone && everest/everest check"`.

**Comment by sishtiaq** [comment]
It should also check that VS is installed, or install it if it's not.

**Comment by msprotz** [comment]
Hmm I guess the high-level description is:
- fetch & launch VS2015 installer with C++ & F# flags
- fetch & launch Cygwin installer with silent mode & wget + git
- c:\cygwin\bin\bash --login -c "./everest check"

What step would Chocolatey help with?

**Comment by sishtiaq** [comment]
A declarative way of handling yr #1 and #2 above.

**Comment by tahina-pro** [comment]
cc8cda79d3318a024d223b12fe9958df208b334a added a PowerShell script file, windows-init.ps1, to install Cygwin and run ./everest check on Windows. (This script also installs GitHub Actions, since it is primarily meant for CI purposes.)
