### ISSUE TITLE
CI build performance improvement:  set EVEREST_SCONS_CACHE_DIR environment variable

### ISSUE THREAD

**Issue by BarryBo** [project-everest/everest#44]
When a project switches from make to SCons, I have the SConstruct file enable caching based on a hierarchy of options:
1. An explicit --cache-dir= switch (either on the Scons command line or in the SCONS environment variable)
2. Project-specific environment variable... FSTAR_SCONS_CACHE_DIR or VALE_SCONS_CACHE_DIR
3. An Everest variable... EVEREST_SCONS_CACHE_DIR

There are two work items here:

1. Ideally, the build machines can set EVEREST_SCONS_CACHE_DIR once, and any CI or build will then leverage the cache.  It just needs to be a writable directory... can be under %tmp%, %home%, anywhere.
2. The "./everest check" script should also recommend setting EVEREST_SCONS_CACHE_DIR into .bashrc, so most/all contributors will automatically take advantage of the cache.

CI performance should improve, for Scons-based projects, assuming that most intermediary files are unchanged from integration to integration, so those will be retrieved from the cache rather than rebuilt.

**Comment by msprotz** [comment]
```
everbld@Everest-CI ~
$ echo $EVEREST_SCONS_CACHE_DIR
C:/cygwin64/tmp/everest
```

(from the `$TEMP` environment variable).
