### ISSUE TITLE
Unsupported OCaml 4.03.0 is not caught by everest check

### ISSUE THREAD

**Issue by R1kM** [project-everest/everest#46]
FStar can't compile with OCaml 4.03.0: Only the versions 4.02, 4.04 and 4.05 are supported by the check in src/ocaml-output/get_branch.ml
./everest check only ensures that the OCaml version is greater that 4.02. This should be checked to avoid errors during ./everest make

**Comment by s-zanella** [comment]
Fixed by https://github.com/project-everest/everest/commit/5896824d376690c17f8bd274ded3701fd18ec5f5
