### ISSUE TITLE
Make `everest make -j 8` behave like `everest -j 8 make`

### ISSUE THREAD

**Issue by tahina-pro** [project-everest/everest#55]
Currently, command line arguments passed to `everest` are strictly interpreted left-to-right, in the exact order in which they were passed.
Some people expressed concern that options such as `-j 8`, then, only apply to actions specified after, not before, thus  `everest make -j 8`  builds sequentially.

One possible solution: the command line arguments could be scanned twice, once to process options such as `-j 8`, then once again to process actions.

**Comment by s-zanella** [comment]
If only we could use `getopt` we could do this, support options and arguments in an arbitrary order, and also fix the common `-j8` vs `-j 8` mistake.
...but Mac OS X ships with an antiquated `getopt` from 2002 that doesn't support long options.

What do you think of asking Mac OS X users to install a newer version with `brew install gnu-getopt` like we do for `gsed`, `gfind`, `greadlink`?

**Comment by msprotz** [comment]
I am strongly in favor of that! Great suggestion.

**Comment by s-zanella** [comment]
I switched to `getopt` in https://github.com/project-everest/everest/tree/santiago_getopt but I don't have a Mac OS X machine to try. The script assumes Homebrew installs `getopt` in `/usr/local/opt/gnu-getopt/bin`

**Comment by msprotz** [comment]
```
gnu-getopt is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have gnu-getopt first in your PATH run:
  echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile
```

so this seems good. thanks!

**Comment by s-zanella** [comment]
I got a CI green and merged the changes in `master` and `mitls_dev`.
