### ISSUE TITLE
quic2c branch: missing ocaml package 'ctypes.foreign.unthreaded'

### ISSUE THREAD

**Issue by kevinmkane** [project-everest/everest#56]
Doing 'everest make' with the quic2c branch (current HEAD is 8669e701) results in the following build failure:

```
make ocaml-all kremlin-all
make[1]: Entering directory '/cygdrive/d/sd/everest/everest/mitls-fstar/src/tls'
rm -rf .depend.OCaml .depend.Kremlin
make -f Makefile.OCaml all
make[2]: Entering directory '/cygdrive/d/sd/everest/everest/mitls-fstar/src/tls'
mkdir -p extract/OCaml
D:/sd/everest/everest/FStar/bin/fstar.exe --cache_dir cache.OCaml --cache_checked_modules  --odir extract/OCaml \
         --lax \
         --dep full \
         --extract '* -Prims -FStar +FStar.Test -CoreCrypto -CryptoTypes -DHDB -LowCProvider -HaclProvider -FFICallbacks -Crypto.AEAD -Crypto.Symmetric -Crypto.Plain -Spec.Loops -Buffer.Utils -C +C.Loops -BufferBytes' \
         --include D:/sd/everest/everest/FStar/contrib/CoreCrypto/fst/ --include D:/sd/everest/everest/hacl-star/secure_api --include D:/sd/everest/everest/hacl-star/secure_api/utils --include D:/sd/everest/everest/hacl-star/secure_api/concrete_specializations --include D:/sd/everest/everest/hacl-star/secure_api/LowCProvider/fst --include D:/sd/everest/everest/hacl-star/code/curve25519/api --include D:/sd/everest/everest/hacl-star/code/lib --include D:/sd/everest/everest/kremlin/kremlib --include ../../libs/ffi --include ./concrete-flags --include ./concrete-flags/OCaml \
         TLS.fst QUIC.fst Test.Main.fst  > .depend.OCaml
OCAMLPATH="D:/sd/everest/everest/FStar/bin" ocamlfind opt -package fstarlib,zarith,ctypes,ctypes.foreign -g -I D:/sd/everest/everest/FStar/ulib/ml -I extract/OCaml -I D:/sd/everest/everest/MLCrypto -I ../../libs/ffi -I D:/sd/everest/everest/hacl-star/secure_api/LowCProvider -I D:/sd/everest/everest/hacl-star/secure_api/out/runtime_switch/ -I D:/sd/everest/everest/kremlin/_build/kremlib -I test -I extract/mlstubs -I . -w -8-11-26-20 -c extract/mlstubs/BufferBytes.ml -o extract/OCaml/BufferBytes.cmx
ocamlfind: Package `ctypes.foreign.unthreaded' not found - required by `ctypes.foreign'
make[2]: *** [Makefile.OCaml:157: extract/OCaml/BufferBytes.cmx] Error 2
make[2]: Leaving directory '/cygdrive/d/sd/everest/everest/mitls-fstar/src/tls'
make[1]: *** [Makefile:16: ocaml-all] Error 2
make[1]: Leaving directory '/cygdrive/d/sd/everest/everest/mitls-fstar/src/tls'
make: *** [Makefile:6: all] Error 2
make: Leaving directory '/cygdrive/d/sd/everest/everest/mitls-fstar/src/tls'
================================================================================



ERROR: build failed for one or more projects
mitls-fstar

```

Searching around revealed the missing package, ctypes.foreign.unthreaded, is included by running "opam install ctypes-foreign". Indeed, after doing this and running 'everest make' again I have a successful build.  Is this something that needs to be added to your scripts?

**Comment by msprotz** [comment]
Is it in the opam-packages file? Perhaps I added it on master and forgot to merge into quic2c which is why Everest check didn't complain?

Thanks,

Jonathan

**Comment by kevinmkane** [comment]
This line is in opam-packages in the quic2c branch:

`ctypes.foreign ctypes-foreign`

That's not in master's version. I was on master when I first set everything up. Then I checked out the quic2c branch. I tried a build first and had this failure, and that's when I ran everest check again now on the quic2c branch. I got the build failure again, and that's when I searched around and installed the package manually.

**Comment by msprotz** [comment]
Do you understand why the everest script didn't detect that the package was missing? There's a part that's supposed to check that all required ocamlfind packages are present

**Comment by kevinmkane** [comment]
I'm guessing, but now that I know what the opam-packages file is for, note that the error message was that ctypes.foreign.unthreaded was not found, and it is required by ctypes.foreign. This suggests ctypes.foreign was present, which may be why the everest script thought all was well. Do you need another line to specify ctypes.foreign.unthreaded is provided by ctypes-foreign so it will check for that package as well?

**Comment by kevinmkane** [comment]
https://github.com/project-everest/everest/pull/57

**Comment by kevinmkane** [comment]
PR#57 merged and fixes this issue.
