### ISSUE TITLE
Error: Unbound module Prims

### ISSUE THREAD

**Issue by bpr** [project-everest/everest#61]
I'm unable to compile any extracted OCaml program on account of a missing Prims module. I installed F* on my MacOS Mojave 10.14.6 (18G103) using Homebrew
```
brian@macbook fstar: fstar.exe --version
F* 0.9.6.0
platform=Darwin_x86_64
compiler=OCaml 4.06.1
date=2018-06-02T06:57:31+0100
commit=743819b (dirty)
```
I extracted the OCaml from a simple hello world FStar using
```
fstar.exe  --odir ./out --codegen OCaml Hello.fst
```

and attempted to compile with 
```
ocamlfind opt out/Hello.ml -o Hello
```

as per the docs. The error message is the title of this issue.

**Comment by s-zanella** [comment]
You need to link in FStar's standard library. E.g.

```OCAMLPATH="$FSTAR_HOME/bin" ocamlfind opt -package fstarlib -linkpkg out/Hello.ml -o Hello```

**Comment by bpr** [comment]
Thanks! It wasn't in the documentation I was reading, but I saw it later when I downloaded the source and looked in the examples directory.
