### ISSUE TITLE
WASM-TEST,Wasm1 failing

### ISSUE THREAD

**Issue by cassiersg** [project-everest/everest#64]
When running the `./everest test` command (fresh build following the [web page](https://project-everest.github.io/)), I get the following error:
```
[...]
⚙ KreMLin auto-detecting tools. Here's what we found:
readlink is: readlink
KreMLin called via: ../_build/src/Kremlin.native
KreMLin home is: /home/cassiersg/everest/kremlin
Wrote WasmSupport.wasm
Wrote Wasm1.wasm
cd .output/Wasm1.wasm && \
  if ! false; then node main.js && echo "\033[01;32m✔\033[00m [WASM-TEST,Wasm1]" || (echo "\033[01;31m✘\033[00m [WASM-TEST,Wasm1]" && false); \
  else ! node main.js && echo "\033[01;32m✔\033[00m [WASM-TEST,Wasm1]" || (echo "\033[01;31m✘\033[00m [WASM-TEST,Wasm1]" && false); fi
node: relocation error: /usr/lib/x86_64-linux-gnu/libnode.so.64: symbol SSL_CTX_set_ciphersuites version OPENSSL_1_1_1 not defined in file libssl.so.1.1 with link time reference
✘ [WASM-TEST,Wasm1]
make: *** [Makefile:196: Wasm1.wasm-test] Error 1
make: Leaving directory '/home/cassiersg/everest/kremlin/test'
```

Version: 131cc2416c
OS: Debian 10

**Comment by msprotz** [comment]
Everest uses (as a transient mechanism) OpenSSL for algorithms that are still missing from EverCrypt. As such, we probably export some LD_LIBRARY_PATH in the everest script that clashes with node which expects a more recent version of OpenSSL. Can you try unsetting LD_LIBRARY_PATH in the `everest` script prior to starting the kremlin tests? (It will still be needed for subsequent tests, like the HACL* and miTLS tests, so it needs to be disabled in a sub-shell.)

Thanks!
