### ISSUE TITLE
`everest check` expects fsharpc, mono to be installed

### ISSUE THREAD

**Issue by naman** [project-everest/everest#76]
What happens now?
Ubuntu 20.04 on WSL
Even after installing mono, dotnet-sdk-3.1 through Ubuntu's package manager. I get the following error while running `everest check`

```
./everest check                                                                      11:40:47
# Switching to the everest directory ... now in /home/-/work/everest

Checking environment
... which found
... github.com access ok
... ocaml minimum version requirements met
... opam found
... all 24 ocamlfind packages found
... sample ocamlbuild project compiles successfully
... Node.js found in PATH
ERROR: fsharpc not found
Hint: brew install mono or use your favorite package manager
```

Expecation:
Ideally, the everest script should be able to install fsharp dependencies.

**Comment by nuaaysh** [comment]
Hello, 
      I meet the same issue "ERROR: fsharpc not found", same environment: Ubuntu 20.04
Any solutions? 
     ps: the docker file is too big, it's impossible for me to use the docker version.

Regards,

**Comment by nuaaysh** [comment]
> Hello,
> I meet the same issue "ERROR: fsharpc not found", same environment: Ubuntu 20.04
> Any solutions?
> ps: the docker file is too big, it's impossible for me to use the docker version.
> 
> Regards,

I try the command: sudo apt install fsharp, now this error is solved. thx @protz
