### ISSUE TITLE
Any help for solving "ERROR: python points to something that is not a Python 2.x"

### ISSUE THREAD

**Issue by tinyoo** [project-everest/everest#87]
./everest check
Although I have altered to 2.7.18, the "ERROR: python points to something that is not a Python 2.x. Please fix this according to your platform" always exits.
Anyone can offer some advice? Thanks a lot!

**Comment by tahina-pro** [comment]
Thanks for notifying us. We figured out that such checks have become obsolete, so we are in the process of removing them (see the abovementioned PR)
